@echo off
REM Chrome native host wrapper script
REM Generated by Claude Code - do not edit manually
"C:\Users\Micro\AppData\Local\hermes\node\node_modules\@anthropic-ai\claude-code\bin\claude.exe" --chrome-native-host
