#!/usr/bin/perl
# Adds dark: variant twins to Tailwind utility classes, preserving hover:/focus:/group-hover: prefixes.
use strict; use warnings;

my $PFX = qr/(hover:|focus:|group-hover:)?/;

while (<>) {
  s/${PFX}text-\[#18181B\]/${1}text-[#18181B] dark:${1}text-[#F4F4F5]/g;
  s/${PFX}text-\[#27272A\]/${1}text-[#27272A] dark:${1}text-[#F4F4F5]/g;
  s/${PFX}text-\[#71717A\]/${1}text-[#71717A] dark:${1}text-[#A1A1AA]/g;
  s/${PFX}border-\[#E4E4E7\]/${1}border-[#E4E4E7] dark:${1}border-[#3F3F46]/g;
  s/${PFX}border-\[#F4F4F5\]/${1}border-[#F4F4F5] dark:${1}border-[#3F3F46]/g;
  s/${PFX}bg-\[#F4F4F5\]/${1}bg-[#F4F4F5] dark:${1}bg-[#3F3F46]/g;
  s/${PFX}bg-\[#E4E4E7\]/${1}bg-[#E4E4E7] dark:${1}bg-[#3F3F46]/g;
  s/${PFX}bg-\[#FAFAFA\]/${1}bg-[#FAFAFA] dark:${1}bg-[#18181B]/g;
  s/(?<!dark:)\bbg-white\b/bg-white dark:bg-[#27272A]/g;

  for my $c (qw(green red blue orange amber purple indigo emerald yellow gray sky teal rose pink)) {
    s/${PFX}bg-$c-(50|100|200)\b/${1}bg-$c-$2 dark:${1}bg-$c-950\/40/g;
    s/${PFX}border-$c-(100|200|300|400)\b/${1}border-$c-$2 dark:${1}border-$c-800/g;
    s/${PFX}text-$c-(500|600|700|800|900)\b/${1}text-$c-$2 dark:${1}text-$c-400/g;
  }
  print;
}
